name = "update-amazon-ips"
account_id = "d704bf18761786d3e83701e3857f1afe"
compatibility_date = "2025-07-18"

# KV namespaces binding
kv_namespaces = [
  { binding = "BOT_BLOCKER_KV", id = "7da99382fc3945bd87bc65f55c9ea1fb" }
]
