# wrangler.toml
name = "shopify-bot-blocker"
account_id = "d704bf18761786d3e83701e3857f1afe"
main = "src/index.js"
compatibility_date = "2025-07-18"

# workers_dev = true # テスト用

# Cron Triggers
[triggers]
crons = ["*/30 * * * *"]

# KV 名前空間
[[kv_namespaces]]
binding = "BOT_BLOCKER_KV"
id = "7da99382fc3945bd87bc65f55c9ea1fb"

# 不要になった LOCALE_FANOUT の定義を削除

# R2 バケット
[[r2_buckets]]
binding = "BLOCKLIST_R2"
bucket_name = "rocaniiru-log"

# Durable Object (名前とクラス名を変更)
[durable_objects]
bindings = [
  { name = "IP_STATE_TRACKER", class_name = "IPStateTracker" },
  { name = "FINGERPRINT_TRACKER", class_name = "FingerprintTracker" } # ★ この行を追加してください ★
]
# ★★★ ここに新しいマイグレーションを追加します ★★★
[[migrations]]
tag = "v5_add_fingerprint_tracker" # 新しいマイグレーションの一意なタグ
new_classes = ["FingerprintTracker"] # 新たにDurable Objectとして登録するクラス名
