# wrangler.toml
name = "shopify-bot-blocker"
account_id = "d704bf18761786d3e83701e3857f1afe"
main = "src/index.js"
compatibility_date = "2025-08-19"

# Cron Triggers
[triggers]
crons = ["0 2 * * 1"] # 週に一度、悪質ボットリストを同期

# KV Namespaces
[[kv_namespaces]]
binding = "BOT_BLOCKER_KV"
id = "7da99382fc3945bd87bc65f55c9ea1fb"

# R2 Buckets
[[r2_buckets]]
binding = "BLOCKLIST_R2"
bucket_name = "rocaniiru-log"

# Durable Object Bindings
[durable_objects]
bindings = [
  { name = "IP_STATE_TRACKER", class_name = "IPStateTracker" },
  { name = "FINGERPRINT_TRACKER", class_name = "FingerprintTracker" }
]

# ★ 修正: Durable Objectのマイグレーションを新しい形式に変更
[[migrations]]
tag = "v7_switch_to_sqlite_backend" # 新しい一意なタグ
new_sqlite_classes = ["IPStateTracker", "FingerprintTracker"]

# [vars]セクションには、公開しても安全な情報のみを記述します
[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAABs5YEksrqKraRyG"

# --- 重要 ---
# 以下のシークレットキーは、`npx wrangler secret put` コマンドで設定します
# TURNSTILE_SECRET_KEY
# TURNSTILE_HMAC_SECRET
# ADMIN_KEY
