name = "shopify-bot-blocker"
account_id = "d704bf18761786d3e83701e3857f1afe"
main = "src/index.js"
compatibility_date = "2025-07-18"
# optional: usage_model = "bundled"
# optional: workers_dev = true

# Bot 判定用 CIDR リスト
[[kv_namespaces]]
binding = "BOT_BLOCKER_KV"
id = "7da99382fc3945bd87bc65f55c9ea1fb"

# ロケールファンアウト制御用
[[kv_namespaces]]
binding = "LOCALE_FANOUT"
id = "c77b138ecd824f499abea59e20c70ad4"  # 取得した ID に置換

# R2バスケット
[[r2_buckets]]
binding = "BLOCKLIST_R2"         # コード内で使う識別子
bucket_name = "rocaniiru-log"    # ダッシュボードで作成したバケット名

# Durable Object
[[durable_objects]]
name = "IPBlockCounter"
class_name = "IPBlockCounter"

[[migrations]]
tag = "v1" # 任意のバージョン名
new_classes = ["IPBlockCounter"]

[durable_objects.bindings]
IP_COUNTER = "IPBlockCounter"
