# wrangler.toml
name = "shopify-bot-blocker"
account_id = "d704bf18761786d3e83701e3857f1afe"
main = "src/index.js"
compatibility_date = "2025-08-18"

[triggers]
crons = ["0 2 * * 1"]

[[kv_namespaces]]
binding = "BOT_BLOCKER_KV"
id = "7da99382fc3945bd87bc65f55c9ea1fb"

[[r2_buckets]]
binding = "BLOCKLIST_R2"
bucket_name = "rocaniiru-log"

[durable_objects]
bindings = [
  { name = "IP_STATE_TRACKER", class_name = "IPStateTrackerV2" },
  { name = "FINGERPRINT_TRACKER", class_name = "FingerprintTrackerV2" }
]

# ここが重要：旧クラス名→新クラス名への “rename” のみを追加
[[migrations]]
tag = "v9_rename_classes_v1_to_v2"
renamed_classes = [
  { from = "IPStateTracker", to = "IPStateTrackerV2" },
  { from = "FingerprintTracker", to = "FingerprintTrackerV2" }
]

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAABs5YEksrqKraRyG"
