name: Update AMAZON_IPS daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-kv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Amazon IP ranges
        run: |
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json \
          | jq '[ .prefixes[] | select(.service=="AMAZON") | .ip_prefix ]' > amazon-ips.json

      - name: Put AMAZON_IPS into KV
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: wrangler kv key put AMAZON_IPS --path=amazon-ips.json --binding=BOT_BLOCKER_KV --config=wrangler.toml --verbose
