name: Update AMAZON_IPS daily

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日 3:00 UTC（日本時間 12:00 実行）

jobs:
  update-kv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AWS IP ranges
        run: |
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json -o ip-ranges.json

      - name: Extract only AMAZON IP prefixes
        run: |
          jq -c '[.prefixes[] | select(.service=="AMAZON") | .ip_prefix]' ip-ranges.json > amazon-ips.json

      - name: Upload to Cloudflare KV
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: |
            wrangler kv:key put --binding=BOT_BLOCKER_KV AMAZON_IPS "$(cat amazon-ips.json)"
