name: Deploy Shopify Bot Blocker

on:
  workflow_dispatch:  # 手動実行可能
  push:
    branches:
      - main           # main ブランチに push されたら実行（ブランチ名に注意）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
