name: Deploy Shopify Bot Blocker

on:
  workflow_dispatch:  # 手動実行可能
  push:
    branches:
      - main           # main ブランチに push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Node & Wrangler
        run: |
          npm install -g wrangler

      - name: Deploy to Cloudflare
        run: |
          npx wrangler publish --config wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
