name: Update IP and Bot Lists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # 毎日18:00 UTC (Amazon IP用)
    - cron: '0 2 * * 1'  # 毎週月曜 02:00 UTC (Bad Bots辞書用)

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm cache clean --force
          npm install -g wrangler@latest

      # --- Job 1: Amazon IP CIDRs を KV にアップロード ---
      - name: Fetch and Prepare IP CIDRs
        run: |
          mkdir -p bot-ip-lists
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json \
          | jq '[.prefixes[] | select(.service=="AMAZON") | .ip_prefix]' \
          > bot-ip-lists/amazon.json

          output_json='{}'
          for file in bot-ip-lists/*.json; do
            key_name=$(basename "$file" .json)
            json_content=$(jq -c . "$file")
            output_json=$(echo "$output_json" \
              | jq --arg key "$key_name" --argjson value "$json_content" \
                  '. + {($key): $value}')
          done
          echo "$output_json" > final-bot-cidrs.json

      - name: Put IP CIDRs into KV
        run: |
          npx wrangler kv key put --namespace-id="7da99382fc3945bd87bc65f55c9ea1fb" "BOT_CIDRS" --path="./final-bot-cidrs.json"

      # --- Job 2: bad-bots.txt を R2 にアップロード ---
      - name: Fetch and Upload Bad Bot Dictionary to R2
        run: |
          curl -s \
            https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bad-bots.txt \
            -o bad-bots.txt
          npx wrangler r2 object put "rocaniiru-log/dictionaries/bad-bots.txt" --file="./bad-bots.txt"
